#Plugins - commented out in case we want to re-enable pagination later
#gems:  [jekyll-paginate]
#paginate: 1
#paginate_path: "/blog/page:num/"

exclude: [post-template.md]

url: "http://www.itspladd.com"
title: "Pladd"
author:
  name: pladd
  email: contact@itspladd.com

permalink: pretty
theme: minimal-mistakes-jekyll

excerpt_separator: <!--more-->
assetspath: "/assets/"
bannerpath: "/assets/banners/"
jspath: "/assets/js/"
iconpath: "/assets/icons/"
drawaboxpath: "/assets/drawabox/"
sketchpath: "/assets/non-artistic-origins/sketch/"
digitamppath: "/assets/non-artistic-origins/digitamp/"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      title: "itspladd"
      shortdesc: "Personal website for Paul Ladd, full-stack web developer."
      author: "pladd"
      preview-image:
        file: "banner.png"
        type: "image/png"
        width: "1200"
        height: "630"
        title: "Pladd"
        alt: "Default \"It's PLADD\" banner."
  -
    scope:
      path: "blog"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "coding"
      type: "posts"
    values:
      layout: "code-project"
  -
    scope:
      path: "writing/rpg_stories"
      type: "posts"
    values:
      layout: "chapter"
  -
    scope:
      path: "writing/rpg_stories/grave-ambush-tirisvale"
    values:
      title: "The Grave Ambush at Tirisvale"
      story: "the Terrence Saga"
      part: "I"
  -
    scope:
      path: "writing/rpg_stories/dwarven-prison-field-trip"
    values:
      title: "Field Trip to the Ancient Dwarven Prison Camp"
      story: "the Terrence Saga"
      part: "X"
