#Plugins - commented out in case we want to re-enable pagination later
#gems:  [jekyll-paginate]
#paginate: 1
#paginate_path: "/blog/page:num/"

name: "Paul Ladd Does Things"
markdown: kramdown

excerpt_separator: <!--more-->

permalink: pretty

defaults:
  -
    scope:
      path: "blog/_posts"
      type: "posts"
    values:
      layout: "post"
      author: "pladd"
  -
    scope:
      path: "writing/rpg_stories"
      type: "posts"
    values:
      layout: "chapter"
      author: "pladd"
  -
    scope:
      path: "writing/rpg_stories/grave-ambush-tirisvale"
      type: "posts"
    values:
      title: "The Grave Ambush at Tirisvale"
      collection: "the Terrence Saga"
      part: "I"