#Plugins - commented out in case we want to re-enable pagination later
#gems:  [jekyll-paginate]
#paginate: 1
#paginate_path: "/blog/page:num/"

url: "http://www.itspladd.com"
name: "PLADD"
author:
  name: pladd
  email: itspladd@gmail.com

excerpt_separator: <!--more-->

permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      title: "PLADD: Paul Ladd Does Words, Art, and Code"
      shortdesc: "Your one-stop shop for blog posts about drawing and stories containing bad words."
      preview-image:
        file: "banner.png"
        type: "image/png"
        width: "1200"
        height: "630"
  -
    scope:
      path: "blog"
      type: "posts"
    values:
      layout: "post"
      author: "pladd"
  -
    scope:
      path: "writing/rpg_stories"
      type: "posts"
    values:
      layout: "chapter"
      author: "pladd"
  -
    scope:
      path: "writing/rpg_stories/grave-ambush-tirisvale"
    values:
      title: "The Grave Ambush at Tirisvale"
      story: "the Terrence Saga"
      part: "I"
  -
    scope:
      path: "writing/rpg_stories/dwarven-prison-field-trip"
    values:
      title: "Field Trip to the Ancient Dwarven Prison Camp"
      story: "the Terrence Saga"
      part: "X"