#Plugins - commented out in case we want to re-enable pagination later
#gems:  [jekyll-paginate]
#paginate: 1
#paginate_path: "/blog/page:num/"

exclude: [post-template.md]

url: "http://www.itspladd.com"
name: "PLADD"
author:
  name: pladd
  email: itspladd@gmail.com

permalink: pretty

excerpt_separator: <!--more-->
bannerpath: "/assets/banners/"
jspath: "/assets/js/"
iconpath: "/assets/icons/"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      title: "PLADD: Paul Ladd Does Words, Art, and Code"
      shortdesc: "Your one-stop shop for blog posts about drawing and stories containing bad words."
      author: "pladd"
      preview-image:
        file: "banner.png"
        type: "image/png"
        width: "1200"
        height: "630"
        title: "Home of the Fightin' Lampreymelons"
        alt: "Default \"It's PLADD\" banner."
  -
    scope:
      path: "blog"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "coding"
      type: "posts"
    values:
      layout: "code-project"
  -
    scope:
      path: "writing/rpg_stories"
      type: "posts"
    values:
      layout: "chapter"
  -
    scope:
      path: "writing/rpg_stories/grave-ambush-tirisvale"
    values:
      title: "The Grave Ambush at Tirisvale"
      story: "the Terrence Saga"
      part: "I"
  -
    scope:
      path: "writing/rpg_stories/dwarven-prison-field-trip"
    values:
      title: "Field Trip to the Ancient Dwarven Prison Camp"
      story: "the Terrence Saga"
      part: "X"
  -
    scope:
      path: "art"
      type: "posts"
    values:
      layout: "art-collection"
  -
    scope:
      path: "art/non-artistic-origins"
    values:
      title: "Paul's Non-Artistic Origins"
  -
    scope:
      path: "art/drawabox"
    values:
      title: "Draw A Box Exercises"