#Plugins - commented out in case we want to re-enable pagination later
#gems:  [jekyll-paginate]
#paginate: 1
#paginate_path: "/blog/page:num/"

name: "PLADD"
url: http://itspladd.github.io
author:
  name: pladd
  email: itspladd@gmail.com

markdown: kramdown


excerpt_separator: <!--more-->

permalink: pretty

defaults:
  -
    scope:
      path: "blog/_posts"
      type: "posts"
    values:
      layout: "post"
      author: "pladd"
  -
    scope:
      path: "writing/rpg_stories"
      type: "posts"
    values:
      layout: "chapter"
      author: "pladd"
  -
    scope:
      path: "writing/rpg_stories/grave-ambush-tirisvale"
    values:
      title: "The Grave Ambush at Tirisvale"
      story: "the Terrence Saga"
      part: "I"
  -
    scope:
      path: "writing/rpg_stories/dwarven-prison-field-trip"
    values:
      title: "Field Trip to the Ancient Dwarven Prison Camp"
      story: "the Terrence Saga"
      part: "X"