#Plugins
gems:  [jekyll-paginate]

name: "Paul Ladd Does Things"
markdown: kramdown
paginate: 1
paginate_path: "/blog/page:num/"

excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
