#Plugins - commented out in case we want to re-enable pagination later
#gems:  [jekyll-paginate]
#paginate: 1
#paginate_path: "/blog/page:num/"

name: "Paul Ladd Does Things"
markdown: kramdown

excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: "blog/_posts"
      type: "posts"
    values:
      layout: "post"